[build]
  command = "npm run build"
  publish = "_site"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template.environment]
  ME = "Your website url (https://example.com/)"
  NAME = "Your name for the h-card"
  GITHUB_TOKEN = "GitHub Personal access token"
  GITHUB_USER = "Username for repo where posts are added to"
  GITHUB_REPO = "Name of repo where posts are added to"